/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project.java_final;

import final_project.java_final.DB_providers.CreatorSQL;
import final_project.java_final.DB_providers.DisplayerDB;
import final_project.java_final.DB_providers.InserterSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 79509
 */
public class NewJFrame extends javax.swing.JFrame {

    
    
    CreatorSQL creatorDB = new CreatorSQL();
    String displayAllRecordsString = "select * from java.all_records";
    InserterSQL inserter = new InserterSQL();
    
    
    
    public NewJFrame() {
        initComponents();
        this.allRecordsTable.setSize(700, 400);
        this.AllRecordsDialog.setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newRecordDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        newRecordTable = new javax.swing.JTable();
        AddRecord = new javax.swing.JButton();
        AllRecordsDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        allRecordsTable = new javax.swing.JTable();
        EditRecordButton = new javax.swing.JButton();
        EditRecordDoneDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        setAccepterBottom = new javax.swing.JButton();
        setMakerBottom = new javax.swing.JButton();
        workAccepterBottom = new javax.swing.JButton();
        workMakerBottom = new javax.swing.JButton();
        RefreshButtom = new javax.swing.JButton();
        CloseRecordButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CreateDBBottom = new javax.swing.JButton();
        AddRecordButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        newRecordDialog.setBackground(new java.awt.Color(51, 51, 51));
        newRecordDialog.setForeground(java.awt.Color.black);

        newRecordTable.setBackground(new java.awt.Color(0, 0, 0));
        newRecordTable.setForeground(new java.awt.Color(0, 102, 204));
        newRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ClientName", "Client Phone", "Client's car number", "Record Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newRecordTable);

        AddRecord.setBackground(new java.awt.Color(0, 0, 0));
        AddRecord.setForeground(new java.awt.Color(204, 204, 255));
        AddRecord.setText("Add Record");
        AddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newRecordDialogLayout = new javax.swing.GroupLayout(newRecordDialog.getContentPane());
        newRecordDialog.getContentPane().setLayout(newRecordDialogLayout);
        newRecordDialogLayout.setHorizontalGroup(
            newRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newRecordDialogLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(AddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        newRecordDialogLayout.setVerticalGroup(
            newRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newRecordDialogLayout.createSequentialGroup()
                .addGroup(newRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newRecordDialogLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(AddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newRecordDialogLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        allRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(allRecordsTable);

        EditRecordButton.setText("edit record");
        EditRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRecordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllRecordsDialogLayout = new javax.swing.GroupLayout(AllRecordsDialog.getContentPane());
        AllRecordsDialog.getContentPane().setLayout(AllRecordsDialogLayout);
        AllRecordsDialogLayout.setHorizontalGroup(
            AllRecordsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllRecordsDialogLayout.createSequentialGroup()
                .addGroup(AllRecordsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllRecordsDialogLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(EditRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AllRecordsDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        AllRecordsDialogLayout.setVerticalGroup(
            AllRecordsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllRecordsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(EditRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel1.setText("You choose record: ");

        setAccepterBottom.setText("set accepter");
        setAccepterBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAccepterBottomActionPerformed(evt);
            }
        });

        setMakerBottom.setText("set maker");

        workAccepterBottom.setText("work");

        workMakerBottom.setText("work");
        workMakerBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workMakerBottomActionPerformed(evt);
            }
        });

        RefreshButtom.setText("refresh");

        CloseRecordButton.setText("Close Record");

        javax.swing.GroupLayout EditRecordDoneDialogLayout = new javax.swing.GroupLayout(EditRecordDoneDialog.getContentPane());
        EditRecordDoneDialog.getContentPane().setLayout(EditRecordDoneDialogLayout);
        EditRecordDoneDialogLayout.setHorizontalGroup(
            EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditRecordDoneDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditRecordDoneDialogLayout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addGroup(EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RefreshButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditRecordDoneDialogLayout.createSequentialGroup()
                        .addComponent(setMakerBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workMakerBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CloseRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(EditRecordDoneDialogLayout.createSequentialGroup()
                        .addComponent(setAccepterBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(workAccepterBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        EditRecordDoneDialogLayout.setVerticalGroup(
            EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditRecordDoneDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workAccepterBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(setAccepterBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(EditRecordDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditRecordDoneDialogLayout.createSequentialGroup()
                        .addComponent(workMakerBottom)
                        .addGap(18, 18, 18)
                        .addComponent(CloseRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(setMakerBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addComponent(RefreshButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateDBBottom.setText("create_DB");
        CreateDBBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDBBottomActionPerformed(evt);
            }
        });

        AddRecordButton.setText("new_record");
        AddRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordButtonActionPerformed(evt);
            }
        });

        jButton3.setText("view_records");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 776, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateDBBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CreateDBBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(AddRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateDBBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDBBottomActionPerformed
        creatorDB.run();
    }//GEN-LAST:event_CreateDBBottomActionPerformed

    private void AddRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordButtonActionPerformed
        // TODO add your handling code here:
        newRecordDialog.setSize(800, 500);
        newRecordDialog.setVisible(true);
        
    }//GEN-LAST:event_AddRecordButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            
            
            
            DisplayerDB displayer = new DisplayerDB(this.displayAllRecordsString);
            
            DefaultTableModel dt = new DefaultTableModel(displayer.getData(), displayer.getColNames());
            
            this.allRecordsTable.setModel(dt );
            
            
            JTable g = new JTable(displayer.getData(), displayer.getColNames())
            {
                public Class getColumnClass(int column){
                    for(int row = 0;row<getRowCount();row++){
                        Object o = getValueAt(row, column);
                        if(o!=null){
                            return o.getClass();
                        }}
                    return Object.class;         }
            };
        } catch (SQLException ex) {     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);  
        }
        
        
        this.AllRecordsDialog.setVisible(true);
        this.allRecordsTable.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordActionPerformed
        // TODO add your handling code here:
        inserter.run("clients", newRecordTable);
        inserter.run("records", newRecordTable);
        

        
    }//GEN-LAST:event_AddRecordActionPerformed

    private void EditRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRecordButtonActionPerformed
        // TODO add your handling code here:
        
        
        int row_number_selected = this.allRecordsTable.getSelectedRow();
        int selected_record_id = (int) this.allRecordsTable.getValueAt(this.allRecordsTable.getSelectedRow(), 0);
        System.out.println("selected_record_id = " + selected_record_id);
        
        
        
        
        
    }//GEN-LAST:event_EditRecordButtonActionPerformed

    private void setAccepterBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAccepterBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setAccepterBottomActionPerformed

    private void workMakerBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workMakerBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workMakerBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecord;
    private javax.swing.JButton AddRecordButton;
    private javax.swing.JDialog AllRecordsDialog;
    private javax.swing.JButton CloseRecordButton;
    private javax.swing.JButton CreateDBBottom;
    private javax.swing.JButton EditRecordButton;
    private javax.swing.JDialog EditRecordDoneDialog;
    private javax.swing.JButton RefreshButtom;
    private javax.swing.JTable allRecordsTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog newRecordDialog;
    private javax.swing.JTable newRecordTable;
    private javax.swing.JButton setAccepterBottom;
    private javax.swing.JButton setMakerBottom;
    private javax.swing.JButton workAccepterBottom;
    private javax.swing.JButton workMakerBottom;
    // End of variables declaration//GEN-END:variables
}
